name: pet
description: A new Flutter project.
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.4
  firebase_analytics: ^6.3.0
  image_picker: ^0.6.7+14
  firebase_database: ^4.4.0

  tflite: ^1.1.1
  flare_flutter: ^2.0.6
  uuid: ^2.2.2
  scoped_model: ^1.1.0
  google_maps_flutter: ^1.0.6
  toast: ^0.1.5
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/pic.png
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/flares/Doggo-storyoggo.flr

  fonts:
    - family: Mitr
      fonts:
        - asset: fonts/Mitr-Regular.ttf

    - family: K2D
      fonts:
        - asset: fonts/K2D-Regular.ttf
